replicaCount: 1
image:
  repository: manojsaikumar/react-article-display
  tag: test-1-ef8fab8eb90d690e436d9cfc216234441282dd93
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ''
fullnameOverride: null
serviceAccount:
  create: true
  name: null
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  port: 80
ingress:
  enabled: true
  annotations: {}
  hosts:
    - paths:
        - /
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
